serverUrl: http://localhost:3000
plugins:
  - 10037   # https://plugins.jetbrains.com/plugin/10037-csv
  - 10080   # https://plugins.jetbrains.com/plugin/10080-rainbow-brackets
  - 10485   # https://plugins.jetbrains.com/plugin/10485-kubernetes
  - 10550   # https://plugins.jetbrains.com/plugin/10550-add-to-gitignore
  - 1065    # https://plugins.jetbrains.com/plugin/1065-checkstyle-idea
  - 10650   # https://plugins.jetbrains.com/plugin/10650-json-parser
  - 10949   # https://plugins.jetbrains.com/plugin/10949-jms-messenger
  - 11058   # https://plugins.jetbrains.com/plugin/11058-extra-icons
  - 12798   # https://plugins.jetbrains.com/plugin/12798-tabnine-ai-code-completion-js-java-python-ts-rust-go-php--more/
  - 1347    # https://plugins.jetbrains.com/plugin/1347-scala
  - 13691   # https://plugins.jetbrains.com/plugin/13691-selenium-ui-testing
  - 14308   # https://plugins.jetbrains.com/plugin/14308-doc-aware-search-everywhere
  - 14877   # https://plugins.jetbrains.com/plugin/14877-jump-to-line
  - 15075   # https://plugins.jetbrains.com/plugin/15075-jpa-buddy
  - 15285   # https://plugins.jetbrains.com/plugin/15285-direnv-integration
  - 16289   # https://plugins.jetbrains.com/plugin/16289-cucumber-
  - 164     # https://plugins.jetbrains.com/plugin/164-ideavim
  - 2162    # https://plugins.jetbrains.com/plugin/2162-string-manipulation
  - 6954    # https://plugins.jetbrains.com/plugin/6954-kotlin
  - 6981    # https://plugins.jetbrains.com/plugin/6981-ini
  - 7017    # https://plugins.jetbrains.com/plugin/7017-plantuml-integration
  - 7125    # https://plugins.jetbrains.com/plugin/7125-grep-console
  - 7157    # https://plugins.jetbrains.com/plugin/7157-javadoc
  - 7160    # https://plugins.jetbrains.com/plugin/7160-camelcase
  - 7177    # https://plugins.jetbrains.com/plugin/7177-file-watchers
  - 7179    # https://plugins.jetbrains.com/plugin/7179-maven-helper
  - 7234    # https://plugins.jetbrains.com/plugin/7234-wrap-to-column
  - 7248    # https://plugins.jetbrains.com/plugin/7248-multirun
  - 7391    # https://plugins.jetbrains.com/plugin/7391-asciidoc
  - 7425    # https://plugins.jetbrains.com/plugin/7425-wakatime
  - 7495    # https://plugins.jetbrains.com/plugin/7495--ignore
  - 7499    # https://plugins.jetbrains.com/plugin/7499-gittoolbox
  - 7724    # https://plugins.jetbrains.com/plugin/7724-docker
  - 7793    # https://plugins.jetbrains.com/plugin/7793-markdown
  - 8527    # https://plugins.jetbrains.com/plugin/8527-google-java-format
  - 8554    # https://plugins.jetbrains.com/plugin/8554-ide-features-trainer
  - 9223    # https://plugins.jetbrains.com/plugin/9223-heap-allocations-viewer
  - 9525    # https://plugins.jetbrains.com/plugin/9525--env-files-support
  - 9746    # https://plugins.jetbrains.com/plugin/9746-ideolog
  - 9792    # https://plugins.jetbrains.com/plugin/9792-key-promoter-x
  - 9836    # https://plugins.jetbrains.com/plugin/9836-randomness
  - 7981    # https://plugins.jetbrains.com/plugin/7981-azure-devops
  - 7535    # https://plugins.jetbrains.com/plugin/7535-gauge
  - 7973    # https://plugins.jetbrains.com/plugin/7973-sonarlint

