name: ci
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".editorconfig"
      - ".gitignore"
      - "config.yml"
      - "docker-compose.yml"
      - "go.mod"
      - "go.sum"
      - "LICENSE"
      - "README.md"
      - "repo-builder.go"
    branches:
      - master

jobs:
  bake-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
